name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- name: Install GTK
    #  run: sudo apt-get install libgtk-3-dev
    - name: Correct Rust Version
      run: rustup install 1.79.0
    - name: Build
      run: cargo build --manifest-path=project/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path=project/Cargo.toml --verbose
    - name: Run clippy
      run: cargo clippy --manifest-path=project/Cargo.toml --all-targets --all-features
